name: publish

on:
  release:
    types: [published]

jobs:
  publish-dignea:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the dignea Docker image
        run: |
          docker build . --tag ghcr.io/dignea/dignea:latest
          docker run ghcr.io/dignea/dignea:latest
          docker push ghcr.io/dignea/dignea:latest
